name: ckfctl
base: core22
adopt-info: ckfctl
summary: A collection of handy tools for operators of kubeflow environments
license: MIT
description: |
  A collection of handy wrapper tools for operators of kubeflow environments

grade: devel
confinement: strict

apps:
  ckfctl:
    command: bin/ckfctl.wrapper
#    completer: etc/bash_completion.d/snap.ckfctl
    plugs:
      - juju-client-observe
      - network
      - network-bind
      - ssh-public-keys
      # Access to config
      - home
      - dot-local-share-juju
      - juju-bin
    environment:
      PATH: $PATH:$SNAP/juju/bin

parts:
  ckfctl-wrapper:
    plugin: dump
    source: bin
    organize:
      ckfctl.wrapper: bin/ckfctl.wrapper

  ckfctl:
    plugin: python
    build-packages:
      - python3-wheel
      - python3-pip
      - python3-setuptools-scm
    source: .
    stage-packages:
      - git
    override-build: |
      craftctl default
      set -e

      # set up bash completion
      # mkdir -p ${CRAFT_PART_INSTALL}/etc/bash_completion.d/
      # echo 'export PATH="${PATH}:/snap/bin:/var/lib/snapd/snap/bin"' > ${CRAFT_PART_INSTALL}/etc/bash_completion.d/snap.ckfctl
      # cat ../src/completions/bash/ckfctl_bash_completion >> ${CRAFT_PART_INSTALL}/etc/bash_completion.d/snap.ckfctl

      # set version
      VERSION=$(python3 setup.py --version)
      echo "Version: ${VERSION}"
      craftctl set version=${VERSION}

plugs:
  dot-local-share-juju:
    interface: personal-files
    write:
      - $HOME/.local/share/juju
  juju-bin:
    interface: content
    content: juju
    target: $SNAP/juju
